version: 0.2

phases:
  pre_build:
    commands:
      - pip install c7n-policystream c7n==$C7N_VERSION
  build:
    commands:
      # run against changed policies
      - c7n-policystream diff -r $POLICY_DIR --target $CODEBUILD_RESOLVED_SOURCE_VERSION --source $POLICYSTREAM_BASE -o /tmp/policystream.yaml
      - cat /tmp/policystream.yaml
      - custodian run /tmp/policystream.yaml -s $OUTPUT_DIR/new -v --dryrun
      - cp deploy/scripts/resolve_base.py /tmp/resolve_base.py
      - cp deploy/scripts/parse_output.py /tmp/parse_output.py
      # now run against the original policies
      - git checkout $POLICYSTREAM_BASE
      - python3 /tmp/resolve_base.py
      - cat /tmp/policystream-original.json
      - custodian run /tmp/policystream-original.json -s $OUTPUT_DIR/original -v --dryrun
  post_build:
    commands:
      # Now parse the outputs
      - python3 /tmp/parse_output.py
