version: 0.2

phases:
  pre_build:
    commands:
      # pull policystream image
      - pip install c7n-policystream
      - c7n-policystream diff -r $POLICY_DIR --target $CODEBUILD_RESOLVED_SOURCE_VERSION --source $POLICYSTREAM_BASE -o policystream.yaml
      - cat policystream.yaml
      # pull the c7n image and run it
      - pip install c7n==$C7N_VERSION
      - custodian run policystream.yaml -s output -v --dryrun
  build:
    commands: []
  post_build:
    commands: []
