version: 0.2

phases:
  pre_build:
    commands:
      # pull policystream image
      - export SOURCE_SHA=$(git rev-parse $POLICYSTREAM_BASE)
      - export CUR_DIR=$(pwd)
      - git checkout $SOURCE_SHA
      - git checkout $CODEBUILD_RESOLVED_SOURCE_VERSION
      - aws ecr get-login-password | docker login --username AWS --password-stdin $POLICYSTREAM_IMAGE_URL
      - docker pull $POLICYSTREAM_IMAGE_URL
      - docker run -v $CUR_DIR:/home/custodian -v $CUR_DIR/.git:/home/custodian/.git $POLICYSTREAM_IMAGE_URL diff -r /home/custodian/$POLICY_DIR --source $CODEBUILD_RESOLVED_SOURCE_VERSION --target $SOURCE_SHA -o /home/custodian/ci/output/policy.yaml
      - cat /ci/output/policy.yaml
      # pull the c7n image and run it
      - export C7N_IMAGE="$C7N_IMAGE_URL:$C7N_IMAGE_TAG"
      - aws ecr get-login-password | docker login --username AWS --password-stdin $C7N_IMAGE
      - docker pull $C7N_IMAGE
      - docker run $C7N_IMAGE
  build:
    commands: []
  post_build:
    commands: []
